#!/bin/sh

LOGFILE=/var/log/petitboot/pb-discover.log
PIDFILE=/var/run/petitboot.pid

case "$1" in
    start)
        ulimit -c unlimited
        mkdir -p $(dirname $LOGFILE)
        PATH=/usr/bin:/usr/sbin:/bin:/sbin pb-discover -l $LOGFILE &
        echo $! > $PIDFILE
        ;;
    stop)
        pid=$(cat $PIDFILE)
        [ -n "$pid" ] && kill -TERM $pid
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
